### ISSUE TITLE
Server returned status 402: Payment Required

### ISSUE THREAD

**Issue by edent** [flathub/com.slack.Slack#124]
> Error: While downloading https://packagecloud.io/slacktechnologies/slack/debian/pool/jessie/main/s/slack-desktop/slack-desktop_4.17.0_amd64.deb: 
> Server returned status 402: Payment Required

**Comment by barthalion** [comment]
It has been just fixed. It will propagate to CDN within 15 minutes.

**Comment by edent** [comment]
Thanks!

**Comment by crispibits-fr** [comment]
As of now (closure time +4 hours) it is still showing:
`Reading package lists... Done
E: Failed to fetch https://packagecloud.io/slacktechnologies/slack/debian/dists/jessie/InRelease  402  Payment Required`
