### ISSUE TITLE
Black screen on Xwayland

### ISSUE THREAD

**Issue by marcelovbcfilho** [flathub/com.slack.Slack#154]
## What happened
I saw that my computer have updated and now it was possible to use Wayland on my GeForce card. So I restarted the computer and selected Gnome on Wayland. Most of the apps are working fine, except for Slack and some others.

## Steps to reproduce
 1. Have a computer with GeForce card and running Fedora 35
 2. Log in using Gnome on Wayland and open slack

## Expected behavior
When using Wayland the app work as expected.

## OS version
Fedora 35

## Software version
Slack:  4.21.1 64-bit
Xwayland: 21.1.3-1.fc35

## Log output
```
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/extra/lib/slack/slack --type=zygote
Initializing local storage instance
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
Gtk-Message: 13:01:41.840: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:01:41.840: Failed to load module "pk-gtk-module"
Gtk-Message: 13:01:41.840: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:01:41.840: Failed to load module "pk-gtk-module"
[2:1116/130141.846771:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Failed to establish dbus connectionLaunchProcess: failed to execvp:
xdg-settings
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2:1116/130141.938245:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1116/130141.938276:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1116/130141.938300:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1116/130141.954772:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1116/130141.954843:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1116/130143.702461:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1116/130143.736665:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1116/130143.736721:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1116/130145.166439:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1116/130145.166502:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
```

## Hardware info
![Screenshot from 2021-11-16 13-02-39](https://user-images.githubusercontent.com/51462138/142020883-4d0c4525-a734-4e40-898d-8450306ab2c7.png)

## Observations
Running with the following parameters did not work, in other apps that use Electrom they've worked.
```--enable-features=UseOzonePlatform --ozone-platform=wayland```

But when I disable the GPU it works.
```--disable-gpu```

**Comment by tfmoraes** [comment]
I'm having this problem too. Thanks @marcelovbcfilho for the `--disable-gpu` workaround.

**Comment by alvarlagerlof** [comment]
> I'm having this problem too. Thanks @marcelovbcfilho for the `--disable-gpu` workaround.

How do I apply this?

**Comment by alvarlagerlof** [comment]
I no longer have this issue

**Comment by pedrovanzella** [comment]
This issue is still present for me. I have to use `--disable-gpu` to get the window to display anything. This is on xwayland, both gnome and kde, with nvidia drivers.

**Comment by marcelovbcfilho** [comment]
This actually was fixed with the latest nvidia drivers 510.47.03, apparently it was a nvidia problem.

**Comment by pedrovanzella** [comment]
Interesting. I'm running 510.47.03 and the problem still exists.

**Comment by marcelovbcfilho** [comment]
Well actually I was wrong, for some reason my SO decided to run slack with the integrated graphics card that is radeon and because of that slack is working for me on wayland... Sorry my bad.

But yes, probably now this is a Slack problem, because chromium that is where slack is build on top of is working ok on wayland with nvidia, they probably need to update the electron version.

In the following image I disabled integrated graphics card on bios and am only using the nvidia one.

![Screenshot from 2022-02-09 13-42-05](https://user-images.githubusercontent.com/51462138/153247567-f8d7dd23-e4b1-4a29-86f3-6e2e1bb3dcf6.png)

**Comment by alvarlagerlof** [comment]
510.47.03 did not fix this for me either. I think it's the app or the flatpak config.

**Comment by alvarlagerlof** [comment]
This seems to be fixed for me now. Does it work for anyone else?

**Comment by marcelovbcfilho** [comment]
Well this is hard for me to answer, I recently changed my GTX card for and Radeon one and with the radeon it works just fine on wayland.

**Comment by pedrovanzella** [comment]
Working for me on nvidia too.
